version: 2
updates:
  - package-ecosystem: bun
    rebase-strategy: "auto"
    directories:
      - "/"
      - "/pkgs/definitions"
      - "/pkgs/integrations/typescript"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    rebase-strategy: "auto"
    directories:
      - "/.github/actions/*"
      - "/.github/workflows"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
