import "./calendario-letivo.model.tsp";
import "./calendario-letivo.dtos.tsp";

import "./grade-horario-oferta-formacao.model.tsp";
import "./grade-horario-oferta-formacao.dtos.tsp";

import "./grade-horario-oferta-formacao-intervalo-de-tempo.model.tsp";
import "./grade-horario-oferta-formacao-intervalo-de-tempo.dtos.tsp";

import "./dia-calendario.model.tsp";
import "./dia-calendario.dtos.tsp";

import "./evento.model.tsp";
import "./evento.dtos.tsp";

import "./etapa.model.tsp";
import "./etapa.dtos.tsp";

import "./grade-horario-oferta-formacao-dtos.tsp";
import "./grade-horario-oferta-formacao-intervalo-de-tempo.dtos.tsp"; 

import "./calendario-dias.dtos.tsp";
import "./calendario-dias.model.tsp";
