name: Auto-Changeset for Dependabot PR

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  add-changeset:
    if: >
      github.event.pull_request.user.login == 'dependabot[bot]'
      && contains(github.event.pull_request.labels.*.name, 'dependencies')
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Detect changed packages
        id: detect
        run: |
          changed=$(git diff --name-only origin/main...HEAD \
            | grep 'package.json' \
            | cut -d'/' -f1 \
            | sort -u \
            | paste -sd ' ' -)
          echo "changed=$changed" >> $GITHUB_OUTPUT

      - name: Generate Changesets
        run: |
          for pkg in ${{ steps.detect.outputs.changed }}; do
            mkdir -p .changeset
            cat <<EOF > .changeset/$pkg.md
            ---
            "$pkg": patch
            ---

            Auto-generated changeset for Dependabot updates in $pkg.
            EOF
          done

      - name: Commit & push Changesets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .changeset
          git commit -m "chore: add changesets for Dependabot updates [skip-dependabot]"
          git push
