# file based on https://github.com/vercel/vercel/blob/5b72741f1c681bbed8ccfe315f3e1126b3f4bde2/.github/workflows/test-lint.yml

name: Lint

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  prebuild-devcontainer:
    uses: ./.github/workflows/prebuild-devcontainer.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      cache-from: ghcr.io/ladesa-ro/domain/devcontainer

  enforce-changeset:
    name: Enforce Changeset
    runs-on: ubuntu-latest

    needs:
      - prebuild-devcontainer

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - run: git fetch origin ${{ github.event.pull_request.head.sha }}:pr-${{ github.event.pull_request.number }}
      - run: git checkout pr-${{ github.event.pull_request.number }}

      - name: Enforce Changeset with changeset:status
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6
        if: ${{ github.event.pull_request.user.login != 'changesets[bot]' }}
        with:
          configFile: .devcontainer/devcontainer.json
          cacheFrom: ghcr.io/ladesa-ro/domain/devcontainer
          runCmd: |
            bun install --frozen-lockfile;
            bun run changeset:status;

  lint:
    name: Lint

    timeout-minutes: 10

    runs-on: ubuntu-latest
    needs: [prebuild-devcontainer]

    steps:
      - uses: actions/checkout@v4

      - name: Static Code and Code Generation Checks
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6
        if: github.event_name == 'pull_request' && github.event.pull_request.title != 'Version Packages'
        with:
          configFile: .devcontainer/devcontainer.json
          cacheFrom: ghcr.io/ladesa-ro/domain/devcontainer
          runCmd: |
            bun install --frozen-lockfile;
            bun run all:code:check;
            bun run all:generate;

      - name: Ensure clean git workspace
        if: github.event_name == 'pull_request' && github.event.pull_request.title != 'Version Packages'
        run: git diff --name-only --exit-code

  summary:
    name: Summary (lint)
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    needs:
      - enforce-changeset
      - lint
    steps:
      - name: Check All
        run: |-
          for status in ${{ join(needs.*.result, ' ') }}
          do
            if [ "$status" != "success" ] && [ "$status" != "skipped" ]
            then
              echo "Some checks failed"
              exit 1
            fi
          done
