# file based on https://github.com/vercel/vercel/blob/5b72741f1c681bbed8ccfe315f3e1126b3f4bde2/.github/workflows/test-lint.yml

name: Lint

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  should-check-for-changeset:

    name: Determine whether to run changeset checks 
    runs-on: ubuntu-latest

    outputs:
      run_checks: ${{ steps.gate.outputs.run_checks }}

    steps:
      - name: Determine whether to run changeset checks
        id: gate
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" && \
                "${{ github.event.pull_request.title }}" != "Version Packages" ]]; then
            echo "run_checks=true" >> $GITHUB_OUTPUT
          else
            echo "run_checks=false" >> $GITHUB_OUTPUT
          fi

  prebuild-devcontainer:
    name: Prebuild dev container
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        # https://github.com/devcontainers/ci/blob/main/docs/github-action.md#inputs
        with:
          configFile: .devcontainer/devcontainer.json
          cacheFrom: ghcr.io/ladesa-ro/domain/devcontainer
          imageName: ghcr.io/ladesa-ro/domain/devcontainer
          refFilterForPush: refs/heads/main
          push: filter

  enforce-changeset:
    name: Enforce Changeset
    runs-on: ubuntu-latest
    
    needs:
      - prebuild-devcontainer
      - should-check-for-changeset

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - run: git fetch origin ${{ github.event.pull_request.head.sha }}:pr-${{ github.event.pull_request.number }}
      - run: git checkout pr-${{ github.event.pull_request.number }}

      - name: Enforce Changeset with changeset:status
        uses: devcontainers/ci@v0.3
        if: ${{ needs.should-check-for-changeset.outputs.run_checks == 'true' }}
        with:
          configFile: .devcontainer/devcontainer.json
          cacheFrom: ghcr.io/ladesa-ro/domain/devcontainer
          runCmd: |
            bun install --frozen-lockfile;
            bun run changeset:status;

  lint:
    name: Lint

    timeout-minutes: 10

    runs-on: ubuntu-latest
    needs: [prebuild-devcontainer]

    steps:
      - uses: actions/checkout@v4

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        if: github.event_name == 'pull_request' && github.event.pull_request.title != 'Version Packages'
        with:
          configFile: .devcontainer/devcontainer.json
          cacheFrom: ghcr.io/ladesa-ro/domain/devcontainer
          runCmd: |
            bun install --frozen-lockfile;
            bun run all:lint:check;
            bun run all:generate;

      - name: Ensure clean git workspace
        if: github.event_name == 'pull_request' && github.event.pull_request.title != 'Version Packages'  
        run: git diff --name-only --exit-code

  summary:
    name: Summary (lint)
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    needs:
      - enforce-changeset
      - lint
    steps:
      - name: Check All
        run: |-
          for status in ${{ join(needs.*.result, ' ') }}
          do
            if [ "$status" != "success" ] && [ "$status" != "skipped" ]
            then
              echo "Some checks failed"
              exit 1
            fi
          done
