name: CI with Changesets - Version PR and Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets-ci:
    name: Changesets CI

    runs-on: ubuntu-latest

    outputs:
      has_changesets: ${{ steps.changeset.outputs.hasChangesets }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          version: "latest"

      - run: bun install --frozen-lockfile

      - id: changeset
        uses: changesets/action@v1
        with:
          version: bun run changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    if: needs.release.outputs.has_changesets == 'false'

    runs-on: ubuntu-latest
    needs: [changesets-ci]

    steps:
      - name: Publish
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/devcontainer.json
          cacheFrom: ghcr.io/ladesa-ro/domain/devcontainer
          runCmd: |
            bun install --frozen-lockfile;
            bun run all:publish;
