import "./disponibilidade.model.tsp";
import "./disponibilidade.dtos.tsp";
import "./disponibilidade-dia.model.tsp";
import "./disponibilidade-dia.dtos.tsp";
import "./turma-disponibilidade.model.tsp";
import "./turma-disponibilidade.dtos.tsp";
import "./professor-disponibilidade.model.tsp";
import "./professor-disponibilidade.dtos.tsp";
import "./diario-preferencia-agrupamento.model.tsp";
import "./diario-preferencia-agrupamento.dtos.tsp";
import "./horario-gerado.model.tsp";
import "./horario-gerado.dtos.tsp";
import "./horario-gerado-aula.model.tsp";
import "./horario-gerado-aula.dtos.tsp";

